### PR TITLE
Show a nice error when running test command without server running

### LINKED ISSUE #427: Better error if `test` command cannot connect to an orchestrator
If you try to run the `test` command from the CLI, but no orchestrator is started, you get a websocket error:

```
$ /Users/cowboyd/Code/CVEX/trade/simulation/node_modules/.bin/bigtest test
Error: websocket server closed connection unexpectedly: [1006] connection failed
    at /Users/cowboyd/Code/CVEX/trade/simulation/node_modules/@bigtest/server/dist/src/client.js:21:23
    at Generator.next (<anonymous>)
    at /Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:8094
    at e.r.advance (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:7730)
    at e.r.trapExit (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:8056)
    at t.n.finalize (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:5567)
    at t.n.resume (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:4921)
    at e.r.advance (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:7776)
    at e.r.trapExit (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:8056)
    at t.n.finalize (/Users/cowboyd/Code/CVEX/trade/simulation/node_modules/effection/dist/effection.js:1:5567)
```

This is true, but not helpful. Instead, we should indicate that the bigtest server is not currently running, and that you can start it with an invocation to `bigtest server`

### PR DESCRIPTION
**Pull request by taras**
Closes #427 

## Motivation

People should know what is happening when an error occurred. They should not have to look at stack traces to figure out what it means. When running tests without bigtest server present, we would get an ugly stack trace that said: `websocket server closed connection unexpectedly`. Instead, we want to show an error that suggests to run `bigtest server` before running tests.

## Approach

Detect when we get `websocket server closed connection unexpectedly` and show error: `Could not connect to BigTest server on ${uri}. Run "bigtest server" to start the server.` instead.

### CODE REVIEW

File: packages/cli/src/run-test.ts [hunk 1]
```diff
@@ -8,9 +8,24 @@ import * as query from './query';
...
+    client = yield Client.create(uri);
+  } catch (e) {
+    if (e.message.includes('websocket server closed connection unexpectedly')) {
+      throw new MainError({ 
+        exitCode: 1,
+        message: `Could not connect to BigTest server on ${uri}. Run "bigtest server" to start the server.`
+      });
+    }
+    throw e;
+  }
```
Comment (cowboyd) [inline packages/cli/src/run-test.ts]: We can wrap the client creation into a single operation, that way no need to re-assign the `client` reference.

```suggestion
  let uri = `ws://localhost:${config.port}`;
  
  let client: Client = yield function*() {
    try {
      return yield Client.create(uri);
    } catch (e) {
      if (e.message.includes('websocket server closed connection unexpectedly')) {
        throw new MainError({ 
          exitCode: 1,
          message: `Could not connect to BigTest server on ${uri}. Run "bigtest server" to start the server.`
        });
      }
      throw e;
    }  
  };
```

File: packages/cli/src/run-test.ts [hunk 2]
```diff
@@ -8,9 +8,24 @@ import * as query from './query';
...
+  let client: Client;
+  let uri = `ws://localhost:${config.port}`;
+
+  try {
+    client = yield Client.create(uri);
+  } catch (e) {
+    if (e.message.includes('websocket server closed connection unexpectedly')) {
+      throw new MainError({ 
+        exitCode: 1,
+        message: `Could not connect to BigTest server on ${uri}. Run "bigtest server" to start the server.`
```
Comment (cowboyd) [inline packages/cli/src/run-test.ts]: Since we use the `runTest` command in both the `ci` and `test` commands, we have a potential weird case where the server stops responding to commands in between when it is started, and when we actually try to connect the client. This should be exceedingly rare, but I figured I'd point it out nonetheless.

File: packages/cli/src/run-test.ts [hunk 3]
```diff
@@ -25,6 +40,7 @@ export function* runTest(config: ProjectOptions, formatter: StreamingFormatter):
       break;
     } else if(result.event) {
       let status = result.event.status;
+      console.log(result.event);
```
Comment (cowboyd) [inline packages/cli/src/run-test.ts]: We should probably enable a linting rule for console.log statements.

File: packages/cli/src/run-test.ts [hunk 4]
```diff
@@ -8,9 +8,24 @@ import * as query from './query';
...
 export function* runTest(config: ProjectOptions, formatter: StreamingFormatter): Operation<void> {
-  let client: Client = yield Client.create(`ws://localhost:${config.port}`);
+
+  let client: Client;
+  let uri = `ws://localhost:${config.port}`;
+
+  try {
+    client = yield Client.create(uri);
+  } catch (e) {
+    if (e.message.includes('websocket server closed connection unexpectedly')) {
```
Comment (cowboyd) [inline packages/cli/src/run-test.ts]: We could also modify the client to throw a more informative error, so that we could ask `e.name === 'NoServerError` or something. That way it would be more robust for future users of `Client`. Not sure how that would work with TypeScript. Thoughts?

**Review by cowboyd — DISMISSED** [review]
I'm wondering if we should have a timeout

File: packages/cli/src/run-test.ts [hunk 5]
```diff
@@ -8,9 +8,25 @@ import * as query from './query';
...
+  let client: Client = yield function*() {
+    try {
+      return yield Client.create(uri);
+    } catch (e) {
+      if (e.message.includes('websocket server closed connection unexpectedly')) {
+        throw new MainError({ 
+          exitCode: 1,
+          message: `Could not connect to BigTest server on ${uri}. Run "bigtest server" to start the server.`
+        });
+      }
```
Comment (jnicklas) [inline packages/cli/src/run-test.ts]: Can we raise a more specific error in the client in case this happens, so we don't have to rely on matching on the error message?

**Review by jnicklas — DISMISSED** [review]

File: packages/cli/src/run-test.ts (hunk 4 above)
Comment (taras) [reply packages/cli/src/run-test.ts]: Done

File: packages/cli/src/run-test.ts (hunk 5 above)
Comment (taras) [reply packages/cli/src/run-test.ts]: Done

Comment (taras) [reply packages/cli/src/run-test.ts]: Oops... nevermind, not done yet.

Comment (taras) [reply packages/cli/src/run-test.ts]: Ok, done now

File: packages/client/src/client.ts [hunk 6]
```diff
@@ -16,13 +17,25 @@ export class Client {
   static *create(url: string): Operation<Client> {
     let socket = new w3cwebsocket(url) as WebSocket;
 
+    yield spawn(function* detectStartupError(): Operation<void> {
+      let [error] = yield once(socket, 'error');
+      
+      if (isYaetiError(error)) {
```
Comment (cowboyd) [inline packages/client/src/client.ts]: I'd call this `isErrorEvent` since Yaeti is just the `nodejs` error event emulator for the [`ErrorEvent`](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent). When the client is running on the browser, it will actually be an `ErrorEvent`

Comment (cowboyd) [reply packages/client/src/client.ts]: Worth noting that on the web, this will _always_ be an error event.

File: packages/client/src/errors.ts [hunk 7]
```diff
@@ -0,0 +1,3 @@
+export class ConnectionAttemptFailed extends Error {
```
Comment (pittst3r) [inline packages/client/src/errors.ts]: Would it be more conventional to name this `ConnectionAttemptFailedError`?

File: packages/client/src/client.ts [hunk 8]
```diff
@@ -16,13 +17,25 @@ export class Client {
   static *create(url: string): Operation<Client> {
     let socket = new w3cwebsocket(url) as WebSocket;
 
+    yield spawn(function* detectStartupError(): Operation<void> {
+      let [error] = yield once(socket, 'error');
+      
+      if (isErrorEvent(error)) {
+        throw new NoServerError(`Could not connect to server at ${url}`);
+      } else {
+        throw error;
```
Comment (cowboyd) [inline packages/client/src/client.ts:26]: I'm trying to imagine a scenario where we execute this code branch, and can't think of one other than a bug in the `websocket` library. Still, it's good to have in case there is and it will throw a big nasty stack trace.

File: packages/client/src/client.ts [hunk 9]
```diff
@@ -16,13 +17,25 @@ export class Client {
   static *create(url: string): Operation<Client> {
     let socket = new w3cwebsocket(url) as WebSocket;
```
Comment (cowboyd) [inline packages/client/src/client.ts:18]: Out of scope for this PR, but in order to make this work in the browser, we're going to have to loosely couple to our underlying websocket library. I wonder what is the best way to do that.

**Review by cowboyd — APPROVED** [review]
Looks great! effection code looking sharp.

**Review by pittst3r — APPROVED** [review]
