### PR TITLE
Fix @bigtest/interaction isPresent page property

### LINKED ISSUE #58: Using `isPresent` without a selector
When omitting `selector` using any of the page object properties, the property uses the page object's root element instead. `isPresent` without the `selector` will throw an error when the root does not exist. It should catch this error and return `false` if either the root or the selector within the root does not exist.

### PR DESCRIPTION
**Pull request by wwilsman**
## Purpose

Fixes #58.

When the `selector` is not provided, the property should work with the page's root element. For `isPresent`, it throws an error when the root does not exist when it should return `false`.

## Approach

Wrap the return statement in a try-catch block that returns `false` when an error is thrown.

Also upgraded the `@bigtest/convergence` dependency to bring in the new convergence timing.

### CODE REVIEW

File: packages/interaction/src/properties/is-present.js [hunk 1]
```diff
@@ -9,6 +9,11 @@ import { computed } from './helpers';
  */
 export default function(selector) {
   return computed(function() {
-    return !!this.$$(selector).length;
+    try {
+      // throws if the root element cannot be found
+      return !!this.$$(selector).length;
+    } catch (e) {
```
Comment (Robdel12) [inline packages/interaction/src/properties/is-present.js]: Does eslint complain about an unused var?

Comment (wwilsman) [reply packages/interaction/src/properties/is-present.js]: Not for `catch` because the `error` var is required

Comment (Robdel12) [reply packages/interaction/src/properties/is-present.js]: TIL. I remember something like that..
