### PR TITLE
Graceful agent shutdown

### LINKED ISSUE #453: Disconnecting agent causes server to crash
Here is a log of connecting an agent (simulated iPad Pro), and then closing that agent with a hard kill (CMD-Q).

```
[connection] connected agent.1
[orchestrator] shutting down!
Error: websocket client closed connection unexpectedly: [1006]
    at /Users/cowboyd/Code/EBSCO/ui-courses/node_modules/@bigtest/effection-express/dist/index.js:53:31
    at Generator.next (<anonymous>)
    at /Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:8094
    at e.r.advance (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:7730)
    at e.r.trapExit (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:8056)
    at t.n.finalize (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:5567)
    at t.n.resume (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:4921)
    at e.r.advance (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:7776)
    at e.r.trapExit (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:8056)
    at t.n.finalize (/Users/cowboyd/Code/EBSCO/ui-courses/node_modules/effection/dist/effection.js:1:5567)
```

### PR DESCRIPTION
**Pull request by cowboyd**
> fixes #453 

Motivation
-----------
As mentioned in #632, The effection-express hard fails on any socket close that isn't 1000 or 1001, but this makes it impossible to handle several valid shutdown scenarios (like when an agent closes because the browser tab was closed)

Approach
----------
This makes the effection-express websocket subscription actually return the close event rather than fail if it's not a "clean close" so that socket handlers can do what they please.

The other key change is that the websocket server _no longer_ waits until the socket is closed before shutting down the operation. This allows the handler to have its own handling of the close event (since before, the context was being shutdown before the child was actually seeing the close event) If you think about it, this makes sense. If you have a handler that wants to return _before_ the socket is closed by the other end, then it can now do so. It's now up to the handle itself to wait until the appropriate time to exit.

Eventually, it will probably be worth it to have a low-level socket abstraction in effection proper that encodes these ideas as well as makes it possible to work with binary data.

### CODE REVIEW

File: packages/server/src/connection-server.ts [hunk 1]
```diff
@@ -35,11 +35,14 @@ export function* createConnectionServer(options: ConnectionServerOptions): Opera
         }
       });
 
-      yield subscribe(connection.events).forEach(function*(message: TestEvent) {
+      let close: CloseEvent = yield subscribe(connection.events).forEach(function*(message: TestEvent) {
```
Comment (jnicklas) [inline packages/server/src/connection-server.ts]: Why not just `let { code, reason }: CloseEvent = `?

**Review by jnicklas — APPROVED** [review]

File: packages/server/src/connection-server.ts (hunk 1 above)
Comment (cowboyd) [reply packages/server/src/connection-server.ts]: Excellent point!
