### PR TITLE
Resolve source maps in error stack traces

### LINKED ISSUE #431: Resolve sources in stack traces that are generated on remote JavaScript runtime
We generate sourcemaps for each test bundle which means that in the browser where an exception occurs, the sources are resolved. However, when the same exception is transmitted across the network, logging it out to the console does not resolve the sources because 

1. it isn't an `Error` class
2. the stack trace was generated by code on a remote JavaScript vm and so the sourcemap is not intrinsically associated with the code.

We need to first figure out how to do this period, possibly by manually loading the sourcemap, and and then figure out how to integrate it into our output.

### Example

```
 AssertionError: expected 2 == 3
|       at _callee$ (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:66693:23)
|       at tryCatch (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:196:23)
|       at Generator.invoke [as _invoke] (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:413:28)
|       at Generator.next (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:249:27)
|       at asyncGeneratorStep (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:861:28)
|       at _next (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:883:13)
|       at http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:890:11
|       at new Promise (<anonymous>)
|       at http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:879:16
|       at _assertEqual (http://localhost:24005/manifest-44d22a51a12a34996032ee8496870689be93fe591ea90818f31fe310be8dfdfc.js:6670
```

### PR DESCRIPTION
**Pull request by jnicklas**
Closes #431

Use the error-stack-parser and get-source packages to extract the source location from stack traces and transform these sources. This gives us vastly improved stack traces.

Also adds support for filtering the stack trace to hide lines from bigtest itself, as well as dependencies from node_modules. The resulting stack traces are very clean. In the future we can make these configurable via options to the CLI.

Example:

```
⨯ [step]       Failing Test -> child -> child second step
|    ERROR: moo
|      test/fixtures/failing.test.ts:14:54 @ _callee2$
```

### CODE REVIEW

File: packages/agent/app/lane.ts [hunk 1]
```diff
@@ -71,7 +64,7 @@ function *runLaneSegment(testRunId: string, agent: Agent, test: TestImplementati
           agent.send({ testRunId, type: 'assertion:result', status: 'ok', path: assertionPath });
         } catch(error) {
           console.error('[agent] assertion failed', assertion, error);
-          agent.send({ testRunId, type: 'assertion:result', status: 'failed', error: serializeError(error), path: assertionPath });
+          agent.send({ testRunId, type: 'assertion:result', status: 'failed', error: yield serializeError(error), path: assertionPath });
```
Comment (cowboyd) [inline packages/agent/app/lane.ts:67]: What do we do if an error occurs in error serialization? I think we need to make sure that this is a very safe thing, because as-is, it could blow up the entire test run.

File: packages/agent/app/serialize-error.ts [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+interface SourceLocation {
+  name?: string;
+  line?: number;
+  column?: number;
+  sourceFile: {
+    path: string;
+  };
+}
+
+export function *serializeError(error: Error): Operation<ErrorDetails> {
```
Comment (cowboyd) [inline packages/agent/app/serialize-error.ts]: Even though our type is `Error` here, I think we can enter this function with values that are not, in fact, errors because the default type of a catch block is `any`. While it should never happen that someone does something like `throw 73;` inside their test cases, I think we should abide by the heuristic: "if something can be thrown, it will be"

File: packages/server/src/manifest-server.ts [hunk 3]
```diff
@@ -7,12 +7,17 @@ interface ManifestServerOptions {
...
+  proxyPort: number;
 };
 
 export function* createManifestServer(options: ManifestServerOptions): Operation {
   let app = express();
 
-  app.raw.use(staticMiddleware(options.dir));
+  app.raw.use(staticMiddleware(options.dir, {
+    setHeaders(res) {
+      res.setHeader('Access-Control-Allow-Origin', `http://localhost:${options.proxyPort}`);
```
Comment (cowboyd) [inline packages/server/src/manifest-server.ts:18]: Is this required so that the stacktrace resolver can fetch the sourcemap?

File: packages/cli/src/query.ts [hunk 4]
```diff
@@ -1,8 +1,8 @@
-import { ResultStatus } from '@bigtest/suite';
+import { ResultStatus, ErrorDetails } from '@bigtest/suite';
 
 export function run() {
   return `
-    subscription {
+    subscription($showInternal: Boolean! = true, $showDependencies: Boolean! = true) {
```
Comment (cowboyd) [inline packages/cli/src/query.ts]: while `showInternal` makes sense as the parameter to the `stack()` property on `ErrorDetails`, it threw me for a loop when I was reading it at the subscription level, can we call these variables `stacktraceShowInternal` and `stacktraceShowDependencies` ?

**Review by cowboyd — COMMENTED** [review]
A few suggestions, but I love it how BigTest does the heavy lifting here to resolve stack traces and provide a convenient way of filtering them over GraphQL. This provides the best of both worlds, where building the best error message is easy, and working with complex stacks is possible.

File: packages/agent/app/lane.ts (hunk 1 above)
Comment (jnicklas) [reply packages/agent/app/lane.ts:67]: Yes, you're right, we should be careful here!

File: packages/agent/app/serialize-error.ts (hunk 2 above)
Comment (jnicklas) [reply packages/agent/app/serialize-error.ts]: Probably true, but what is a good way of disambiguating here? Should we just check `typeof`?

File: packages/server/src/manifest-server.ts (hunk 3 above)
Comment (jnicklas) [reply packages/server/src/manifest-server.ts:18]: Exactly.

**Review by taras — COMMENTED** [review]
Does it make sense to remove the invocation function because it's not very helpful at the moment: `@ _callee2$`

**Comment by jnicklas** [comment]
@taras yeah, I've been unable to get better information for the function name, but I still think that it could be useful sometimes, e.g. if the error is thrown in a helper method or something. Maybe we could make this nicer to read through using terminal colors, we could de-emphasize the function name, but still render it.

**Comment by taras** [comment]
@jnicklas is it possible to get the actual code at that line?

File: packages/agent/app/serialize-error.ts (hunk 2 above)
Comment (cowboyd) [reply packages/agent/app/serialize-error.ts]: Maybe we could duck type on  a `stack` property or whatever is used by `ErrorStackParser.parse()`?

**Comment by jnicklas** [comment]
@taras yes it is, `getSource` makes it pretty simple to get the code at the location.

File: packages/agent/app/serialize-error.ts (hunk 2 above)
Comment (dagda1) [reply packages/agent/app/serialize-error.ts]: You could have a type guard

```typescript
function isError(error: Error | any): error is Error {
  return error instanceof Error;
}
```

That is where the line below that was queried in one of my previous PRs comes in for `BundlerError`

```typescript
Object.setPrototypeOf(this, new.target.prototype);
```

All custom errors should do this IMO.  It should be added to `AmbiguousElementError` and friends

type guards also type narrow so you could  have it

`*serializeError(error: unknown)`

If the type guard returns true then the type is narrowed to the Error class

Comment (jnicklas) [reply packages/agent/app/serialize-error.ts]: @dagda1 I think pretty much all the errors we use inherit from `error` via `class SomeError extends Error`, this should satisfy the `instanceof` check, no prototype trickery necessary.

Comment (dagda1) [reply packages/agent/app/serialize-error.ts]: @jnicklas the reason I mention it is [this](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#example).

I've always believed it was necessary as according to the link, the prototype chain is broken and needs to be restored.

Definitely not saying you must do this

**Comment by jnicklas** [comment]
@taras I added support for getting the source at the error location, but it is disabled by default. We should add some parameters to the CLI to show these, but I didn't want to bloat this PR up even further.

File: packages/cli/src/query.ts [hunk 5]
```diff
@@ -11,10 +11,18 @@ export function run() {
...
+            fileName
+            code @include(if: $showStackTraceCode)
+            line
+            column
+            source {
+              fileName
+              line
+              column
+            }
+          }
```
Comment (taras) [inline packages/cli/src/query.ts:25]: WOW

**Review by taras — APPROVED** [review]
👍
